; ---------------------------------------------------------------------------
; A ProTracker 3 player.
;
; The module is a tracker file: patterns of commands, samples that shape each
; note frame by frame, and ornaments that bend it about.  None of that is a
; register dump — the engine lives in the tracker, so it has to live here too.
; It is worth the ~1.5K: this module is 6K and plays for a minute and a half,
; where the same music as a stream of AY registers came to 27K packed, and 72K
; raw.  Those numbers are why this file exists.
;
; The semantics are ported from Vince Weaver's pt3_lib, which is itself checked
; frame for frame against Bulba's ay_emul — the format's own documentation is
; silent on most of what a player actually has to do, and guessing at it sounds
; approximately right, which is the worst outcome.
;   http://www.deater.net/weave/vmwprod/pt3_lib/
;
; Two tables the module does not carry are generated by the build script into
; pt3tables.inc: which AY period a note means, and how a sample's amplitude and
; a line's volume combine.  See scripts/build-demo.py.
;
; Called once a frame from the main loop, after HALT, like everything else.
; ---------------------------------------------------------------------------

; A channel's state.  Bytes unless it says word; the signed ones are the
; sliding accumulators, which go both ways.
c_enabled  equ  0
c_envon    equ  1
c_volume   equ  2
c_note     equ  3
c_sampptr  equ  4               ; word, and an address, not an offset
c_samploop equ  6
c_samplen  equ  7
c_samppos  equ  8
c_ornptr   equ  9               ; word
c_ornloop  equ  11
c_ornlen   equ  12
c_ornpos   equ  13
c_tone     equ  14              ; word, what the AY is given
c_toneacc  equ  16              ; word, signed
c_slide    equ  18              ; word, signed
c_step     equ  20              ; word, signed
c_delta    equ  22              ; word, signed
c_scount   equ  24
c_sdelay   equ  25
c_slideto  equ  26
c_simple   equ  27              ; a glissando that never arrives anywhere
c_ampsl    equ  28              ; signed
c_amp      equ  29
c_noisesl  equ  30              ; signed
c_envsl    equ  31              ; signed
c_onoff    equ  32              ; the vibrato's countdown
c_onoffd   equ  33
c_offond   equ  34
c_addr     equ  35              ; word, where this channel is in its pattern
c_len      equ  37
c_lencount equ  38
c_done     equ  39
c_size     equ  40

; Where things are in the module's own header.
h_freqtab  equ  $63
h_speed    equ  $64
h_length   equ  $65
h_loop     equ  $66
h_patterns equ  $67
h_samples  equ  $69
h_ornament equ  $a9
h_position equ  $c9

; --- starting up ------------------------------------------------------------

pt3init:
        ld   hl,pt3state        ; every channel and every global, from zero
        ld   bc,pt3end - pt3state
        xor  a
        call fill

        ld   a,(module + h_speed)
        ld   (speed),a
        ld   a,(module + h_length)
        ld   (musiclen),a
        ld   a,(module + h_loop)
        ld   (looppos),a

        ld   hl,(module + h_patterns)
        ld   de,module
        add  hl,de
        ld   (patternloc),hl    ; the table of three addresses per pattern

        ld   hl,module + h_position
        ld   (poslist),hl

        ld   ix,chan_a
        call pt3voice
        ld   ix,chan_b
        call pt3voice
        ld   ix,chan_c
        call pt3voice

        xor  a
        ld   (position),a
        ld   (line),a
        ld   (delaycnt),a
        call setpattern
        ret

; A channel as the tracker leaves it: full volume, silent, sample one and
; ornament zero loaded, so that a pattern which plays a note before it names a
; sample still has one.
pt3voice:
        ld   (ix+c_volume),15
        ld   (ix+c_len),1
        ld   (ix+c_lencount),1
        ld   a,1
        call loadsample
        xor  a
        call loadornament
        ret

; a = which sample, ix = the channel.
;
; Both of these keep hl, because the decoder is walking the pattern with it and
; a sample change in the middle of a line would otherwise leave the channel
; pointed into its own sample data — which sounds exactly like the noise it is.
loadsample:
        push hl
        add  a,a
        ld   e,a
        ld   d,0
        ld   hl,module + h_samples
        add  hl,de
        ld   e,(hl)
        inc  hl
        ld   d,(hl)
        ld   hl,module
        add  hl,de              ; the sample: loop, length, then four bytes a line
        ld   a,(hl)
        ld   (ix+c_samploop),a
        inc  hl
        ld   a,(hl)
        ld   (ix+c_samplen),a
        inc  hl
        ld   (ix+c_sampptr),l
        ld   (ix+c_sampptr+1),h
        pop  hl
        ret

; a = which ornament, ix = the channel.
loadornament:
        push hl
        add  a,a
        ld   e,a
        ld   d,0
        ld   hl,module + h_ornament
        add  hl,de
        ld   e,(hl)
        inc  hl
        ld   d,(hl)
        ld   hl,module
        add  hl,de
        ld   a,(hl)
        ld   (ix+c_ornloop),a
        inc  hl
        ld   a,(hl)
        ld   (ix+c_ornlen),a
        inc  hl
        ld   (ix+c_ornptr),l
        ld   (ix+c_ornptr+1),h
        pop  hl
        ret

; The three patterns this position plays.  A position byte is already the
; pattern number times three, and a pattern is six bytes of the table, so the
; offset into it is the byte doubled and nothing else.
setpattern:
        ld   a,(position)
        ld   e,a
        ld   d,0
        ld   hl,(poslist)
        add  hl,de
        ld   l,(hl)
        ld   h,0
        add  hl,hl
        ld   de,(patternloc)
        add  hl,de

        ld   ix,chan_a
        call onepattern
        ld   ix,chan_b
        call onepattern
        ld   ix,chan_c
        call onepattern

        xor  a
        ld   (noiseper),a
        ret

; hl -> two bytes of the pattern table; leaves hl past them.
onepattern:
        ld   e,(hl)
        inc  hl
        ld   d,(hl)
        inc  hl
        push hl
        ld   hl,module
        add  hl,de
        ld   (ix+c_addr),l
        ld   (ix+c_addr+1),h
        ld   (ix+c_done),0
        pop  hl
        ret

; --- a frame ---------------------------------------------------------------

pt3frame:
        ld   a,(delaycnt)
        or   a
        jr   nz,pf1
        call newline
pf1:    ld   hl,delaycnt
        dec  (hl)
        call makeframe
        jp   ayout

; The next line of the three patterns, and the next pattern when they run out.
; A line that reports the end of its pattern is not played, which is what the
; tracker does; the count is a guard, since a module whose patterns were all
; empty would otherwise spin here for ever.
newline:
        ld   a,8                ; the guard lives in memory: decoding a line
        ld   (tries),a          ; needs every register there is
nl_again:
        ld   a,(line)
        cp   64
        jr   c,nl_line
        call nextpos
nl_line:
        call decodeline
        or   a
        jr   z,nl_ok
        ld   hl,tries
        dec  (hl)
        jr   z,nl_ok            ; nothing but empty patterns: carry on anyway
        call nextpos
        jr   nl_again
nl_ok:
        ld   hl,line
        inc  (hl)
        ld   a,(speed)
        ld   (delaycnt),a
        ret

nextpos:
        xor  a
        ld   (line),a
        ld   a,(position)
        inc  a
        ld   hl,musiclen
        cp   (hl)
        jr   c,np1
        ld   a,(looppos)
np1:    ld   (position),a
        jp   setpattern

; a = 1 when all three channels have reached the end of their pattern.
decodeline:
        ld   ix,chan_a
        call decode
        ld   ix,chan_b
        call decode
        ld   ix,chan_c
        call decode
        ld   a,(chan_a + c_done)
        ld   hl,chan_b + c_done
        and  (hl)
        ld   hl,chan_c + c_done
        and  (hl)
        ret

; --- decoding one line of one channel --------------------------------------
;
; A line is a run of command bytes ending in a note, a rest or an explicit end;
; effects come after that, and their parameters after the byte that ended the
; note.  hl walks the pattern the whole way through, so no case may clobber it.
decode:
        xor  a
        ld   (spec),a
        ld   a,(ix+c_note)
        ld   (prevnote),a
        ld   l,(ix+c_slide)
        ld   h,(ix+c_slide+1)
        ld   (prevslide),hl

        ld   a,(ix+c_lencount)  ; the note is still running
        cp   2
        jp   c,dc_read
        dec  (ix+c_lencount)
        ret

dc_read:
        ld   a,(ix+c_len)
        ld   (ix+c_lencount),a
        ld   l,(ix+c_addr)
        ld   h,(ix+c_addr+1)
        ld   a,(hl)
        ld   b,a

        or   a                  ; $00, the end of the pattern
        jp   nz,dc_effect
        ld   (ix+c_lencount),0
        ld   (ix+c_done),1
        jp   dc_finish

dc_effect:
        cp   $10                ; $01-$0f, an effect this line
        jp   nc,dc_envelope
        ld   (spec),a
        jp   dc_more

dc_envelope:
        cp   $20                ; $10-$1f, the envelope, then a sample
        jp   nc,dc_noise
        ld   a,b
        and  $0f
        jp   z,dc_envoff
        ld   (envtype),a
        ld   a,$78              ; a value it cannot be, so the shape is written
        ld   (envtypeold),a
        inc  hl
        ld   d,(hl)             ; the period, big endian here alone
        inc  hl
        ld   e,(hl)
        ld   (envper),de
        ld   (ix+c_envon),1
        ld   de,0
        ld   (envslide),de
        xor  a
        ld   (envdelay),a
        jp   dc_envsample
dc_envoff:
        ld   (ix+c_envon),0
dc_envsample:
        inc  hl
        ld   a,(hl)
        srl  a                  ; a sample number, doubled
        call loadsample
        ld   (ix+c_ornpos),0
        jp   dc_more

dc_noise:
        cp   $40                ; $20-$3f, the noise period
        jp   nc,dc_ornament
        ld   a,b
        sub  $20
        ld   (noiseper),a
        jp   dc_more

dc_ornament:
        cp   $50                ; $40-$4f, the ornament
        jp   nc,dc_note
        ld   a,b
        and  $0f
        call loadornament
        ld   (ix+c_ornpos),0
        jp   dc_more

dc_note:
        cp   $b0                ; $50-$af, a note, and everything resets
        jp   nc,dc_bee
        ld   a,b
        sub  $50
        ld   (ix+c_note),a
        call restart
        ld   (ix+c_enabled),1
        jp   dc_finish

dc_bee: cp   $c0
        jp   nc,dc_volume
        ld   a,b
        cp   $b0                ; envelope off
        jp   nz,dc_skip
        ld   (ix+c_envon),0
        ld   (ix+c_ornpos),0
        jp   dc_more
dc_skip:
        cp   $b1                ; how many lines this note lasts
        jp   nz,dc_setenv
        inc  hl
        ld   a,(hl)
        ld   (ix+c_len),a
        ld   (ix+c_lencount),a
        jp   dc_more
dc_setenv:                      ; $b2-$bf, the envelope again, without a sample
        ld   (ix+c_envon),1
        ld   a,$78
        ld   (envtypeold),a
        ld   a,b
        and  $0f
        dec  a
        ld   (envtype),a
        inc  hl
        ld   d,(hl)
        inc  hl
        ld   e,(hl)
        ld   (envper),de
        ld   (ix+c_ornpos),0
        ld   de,0
        ld   (envslide),de
        xor  a
        ld   (envdelay),a
        jp   dc_more

dc_volume:
        cp   $d0
        jp   nc,dc_sample
        ld   a,b
        and  $0f                ; $c0, silence; $c1-$cf, the volume
        jp   z,dc_off
        ld   (ix+c_volume),a
        jp   dc_more
dc_off: call restart
        ld   (ix+c_enabled),0
        jp   dc_finish

dc_sample:
        cp   $f0
        jp   nc,dc_both
        ld   a,b                ; $d0, the line is done; $d1-$ef, a sample
        cp   $d0
        jp   z,dc_finish
        sub  $d0
        call loadsample
        jp   dc_more

dc_both:                        ; $f0-$ff, an ornament and then a sample
        ld   (ix+c_envon),0
        ld   (ix+c_ornpos),0
        ld   a,b
        and  $0f
        call loadornament
        inc  hl
        ld   a,(hl)
        srl  a
        call loadsample
        jp   dc_more

; Round again for the next command byte of this line.
dc_more:
        inc  hl
        ld   (ix+c_addr),l
        ld   (ix+c_addr+1),h
        jp   dc_read

; The line is settled; what follows is the effect's parameters, if any.
dc_finish:
        inc  hl
        ld   a,(spec)
        or   a
        jp   z,dc_store

        cp   $01
        jp   z,fx_gliss
        cp   $02
        jp   z,fx_porta
        cp   $03
        jp   z,fx_samppos
        cp   $04
        jp   z,fx_ornpos
        cp   $05
        jp   z,fx_vibrato
        cp   $08
        jp   z,fx_envgliss
        cp   $09
        jp   z,fx_speed
        ; an effect this player does not know: its parameters are unread, so
        ; the rest of the pattern would be nonsense.  Better silent than that.
        ld   (ix+c_enabled),0

dc_store:
        ld   (ix+c_addr),l
        ld   (ix+c_addr+1),h
        ret

; $01, glissando: slide by a step every so many frames, for ever.
fx_gliss:
        ld   a,(hl)
        ld   (ix+c_sdelay),a
        ld   (ix+c_scount),a
        inc  hl
        ld   a,(hl)
        ld   (ix+c_step),a
        inc  hl
        ld   a,(hl)
        ld   (ix+c_step+1),a
        inc  hl
        ld   (ix+c_simple),1
        ld   (ix+c_onoff),0
        jp   dc_store

; $02, portamento: slide from the note that was playing to this one, and stop
; there.  The step's sign is whichever way that is.
fx_porta:
        ld   a,(hl)
        ld   (ix+c_sdelay),a
        ld   (ix+c_scount),a
        inc  hl
        inc  hl
        inc  hl
        ld   a,(hl)
        ld   e,a
        inc  hl
        ld   a,(hl)
        ld   d,a
        inc  hl
        push hl
        ld   (ix+c_simple),0
        ld   (ix+c_onoff),0

        ; the step, as a distance rather than a direction
        ld   a,d
        bit  7,a
        jr   z,fp1
        ld   hl,0               ; negate it
        or   a
        sbc  hl,de
        ex   de,hl
fp1:    ld   (ix+c_step),e
        ld   (ix+c_step+1),d

        ; how far there is to go: this note's period less the old one's
        ld   a,(ix+c_note)
        call notefreq
        push hl
        ld   a,(prevnote)
        call notefreq
        pop  de
        ex   de,hl
        or   a
        sbc  hl,de              ; delta = new - old
        ld   (ix+c_delta),l
        ld   (ix+c_delta+1),h

        ld   a,(ix+c_note)
        ld   (ix+c_slideto),a
        ld   a,(prevnote)
        ld   (ix+c_note),a      ; and start from where we were

        ; if the way to go is downwards, so is the step
        ld   e,(ix+c_slide)
        ld   d,(ix+c_slide+1)
        or   a
        sbc  hl,de              ; delta - sliding
        bit  7,h
        jr   z,fp2
        ld   hl,0
        ld   e,(ix+c_step)
        ld   d,(ix+c_step+1)
        or   a
        sbc  hl,de
        ld   (ix+c_step),l
        ld   (ix+c_step+1),h
fp2:    pop  hl
        jp   dc_store

; $03 and $04: start part way into the sample or the ornament.
fx_samppos:
        ld   a,(hl)
        ld   (ix+c_samppos),a
        inc  hl
        jp   dc_store
fx_ornpos:
        ld   a,(hl)
        ld   (ix+c_ornpos),a
        inc  hl
        jp   dc_store

; $05, vibrato: the channel is switched off and on again, so many frames each.
fx_vibrato:
        ld   a,(hl)
        ld   (ix+c_onoffd),a
        ld   (ix+c_onoff),a
        inc  hl
        ld   a,(hl)
        ld   (ix+c_offond),a
        inc  hl
        ld   (ix+c_scount),0
        ld   (ix+c_slide),0
        ld   (ix+c_slide+1),0
        jp   dc_store

; $08, the envelope's own glissando.
fx_envgliss:
        ld   a,(hl)
        ld   (envdelay),a
        ld   (envdelayorig),a
        inc  hl
        ld   e,(hl)
        inc  hl
        ld   d,(hl)
        inc  hl
        ld   (envslideadd),de
        jp   dc_store

; $09, a new speed for everything.
fx_speed:
        ld   a,(hl)
        ld   (speed),a
        inc  hl
        jp   dc_store

; What a new note, or a rest, clears.
restart:
        ld   (ix+c_samppos),0
        ld   (ix+c_ampsl),0
        ld   (ix+c_noisesl),0
        ld   (ix+c_envsl),0
        ld   (ix+c_ornpos),0
        ld   (ix+c_scount),0
        ld   (ix+c_slide),0
        ld   (ix+c_slide+1),0
        ld   (ix+c_toneacc),0
        ld   (ix+c_toneacc+1),0
        ld   (ix+c_onoff),0
        ret

; a = a note, 0..95; out: hl = the period it means.
notefreq:
        ld   l,a
        ld   h,0
        add  hl,hl
        ld   de,periods
        add  hl,de
        ld   e,(hl)
        inc  hl
        ld   d,(hl)
        ex   de,hl
        ret

; --- what the chip is told, once a frame -----------------------------------

makeframe:
        xor  a
        ld   (mixer),a
        ld   hl,0
        ld   (envadd),hl

        ld   ix,chan_a
        call calcnote
        ld   ix,chan_b
        call calcnote
        ld   ix,chan_c
        call calcnote

        ld   hl,(chan_a + c_tone)
        ld   (ayregs + 0),hl
        ld   hl,(chan_b + c_tone)
        ld   (ayregs + 2),hl
        ld   hl,(chan_c + c_tone)
        ld   (ayregs + 4),hl

        ld   a,(noiseper)
        ld   hl,noiseadd
        add  a,(hl)
        and  $1f
        ld   (ayregs + 6),a

        ld   a,(mixer)
        ld   (ayregs + 7),a

        ld   a,(chan_a + c_amp)
        ld   (ayregs + 8),a
        ld   a,(chan_b + c_amp)
        ld   (ayregs + 9),a
        ld   a,(chan_c + c_amp)
        ld   (ayregs + 10),a

        ld   hl,(envper)
        ld   de,(envadd)
        add  hl,de
        ld   de,(envslide)
        add  hl,de
        ld   (ayregs + 11),hl

        ; The shape register is only written when it changes: writing it at all
        ; restarts the envelope, which is audible as a click on every frame.
        ld   a,(envtype)
        ld   hl,envtypeold
        cp   (hl)
        jr   z,mf_delay
        ld   (hl),a
        ld   (ayregs + 13),a
        ld   a,1
        ld   (envwrite),a

mf_delay:
        ld   a,(envdelay)
        or   a
        ret  z
        dec  a
        ld   (envdelay),a
        ret  nz
        ld   a,(envdelayorig)
        ld   (envdelay),a
        ld   hl,(envslide)
        ld   de,(envslideadd)
        add  hl,de
        ld   (envslide),hl
        ret

; --- one channel, one frame ------------------------------------------------
;
; The sample says what to do this frame: a tone to add, an amplitude, whether
; to slide either of them, and which of tone and noise the mixer should let
; through.  The ornament bends the note.  Both then step on, and both loop.
calcnote:
        ld   a,(ix+c_enabled)
        or   a
        jp   z,cn_silent

        ld   e,(ix+c_samppos)   ; four bytes a line, and a sample can be long
        ld   d,0
        sla  e
        rl   d
        sla  e
        rl   d
        ld   l,(ix+c_sampptr)
        ld   h,(ix+c_sampptr+1)
        add  hl,de

        ld   a,(hl)
        ld   (b0),a
        inc  hl
        ld   a,(hl)
        ld   (b1),a
        inc  hl
        ld   e,(hl)
        inc  hl
        ld   d,(hl)             ; de = the tone this line of the sample adds

        ld   l,(ix+c_toneacc)
        ld   h,(ix+c_toneacc+1)
        add  hl,de
        ld   a,(b1)
        and  $40
        jr   z,cn_tone
        ld   (ix+c_toneacc),l   ; an accumulating sample keeps its total
        ld   (ix+c_toneacc+1),h
cn_tone:
        ld   (tonetmp),hl

        ld   l,(ix+c_ornptr)    ; the ornament, which is signed
        ld   h,(ix+c_ornptr+1)
        ld   e,(ix+c_ornpos)
        ld   d,0
        add  hl,de
        ld   a,(hl)
        add  a,(ix+c_note)
        cp   96                 ; and the note it makes has to exist
        jp   c,cn_freq
        bit  7,a
        jr   z,cn_top
        xor  a
        jp   cn_freq
cn_top: ld   a,95
cn_freq:
        call notefreq
        ld   de,(tonetmp)
        add  hl,de
        ld   e,(ix+c_slide)
        ld   d,(ix+c_slide+1)
        add  hl,de
        ld   a,h
        and  $0f                ; the AY's period is twelve bits
        ld   h,a
        ld   (ix+c_tone),l
        ld   (ix+c_tone+1),h

        ; the slide, if one is running
        ld   a,(ix+c_scount)
        or   a
        jp   z,cn_amp
        dec  a
        ld   (ix+c_scount),a
        jp   nz,cn_amp
        ld   l,(ix+c_slide)
        ld   h,(ix+c_slide+1)
        ld   e,(ix+c_step)
        ld   d,(ix+c_step+1)
        add  hl,de
        ld   (ix+c_slide),l
        ld   (ix+c_slide+1),h
        ld   a,(ix+c_sdelay)
        ld   (ix+c_scount),a
        ld   a,(ix+c_simple)
        or   a
        jp   nz,cn_amp          ; a glissando has nowhere to arrive

        ld   e,(ix+c_delta)     ; a portamento does: has it got there?
        ld   d,(ix+c_delta+1)
        ld   a,(ix+c_step+1)
        bit  7,a
        jr   z,cn_reach
        ex   de,hl              ; sliding down, so the test is the other way
cn_reach:
        or   a
        sbc  hl,de
        bit  7,h
        jp   nz,cn_amp
        ld   a,(ix+c_slideto)
        ld   (ix+c_note),a
        ld   (ix+c_scount),0
        ld   (ix+c_slide),0
        ld   (ix+c_slide+1),0

cn_amp:
        ld   a,(b1)
        and  $0f
        ld   c,a                ; the amplitude the sample asks for
        ld   a,(b0)
        bit  7,a
        jr   z,cn_amp2
        bit  6,a
        jr   z,cn_quieter
        ld   a,(ix+c_ampsl)     ; louder, to a limit
        cp   15
        jr   z,cn_amp2
        inc  (ix+c_ampsl)
        jr   cn_amp2
cn_quieter:
        ld   a,(ix+c_ampsl)
        cp   -15 & $ff
        jr   z,cn_amp2
        dec  (ix+c_ampsl)
cn_amp2:
        ld   a,c
        add  a,(ix+c_ampsl)
        bit  7,a
        jr   z,cn_amp3
        xor  a
        jr   cn_amp4
cn_amp3:
        cp   16
        jr   c,cn_amp4
        ld   a,15
cn_amp4:
        ld   e,a                ; and the line's volume decides the rest
        ld   d,0
        ld   hl,volumes
        add  hl,de
        ld   a,(ix+c_volume)
        add  a,a
        add  a,a
        add  a,a
        add  a,a
        ld   e,a
        ld   d,0
        add  hl,de
        ld   c,(hl)

        ld   a,(b0)             ; and whether the envelope plays it
        and  $01
        jr   nz,cn_slide
        ld   a,(ix+c_envon)
        or   a
        jr   z,cn_slide
        set  4,c
cn_slide:
        ld   (ix+c_amp),c

        ld   a,(b1)             ; the same two bits mean envelope or noise
        bit  7,a
        jr   z,cn_noise

        ld   a,(b0)
        bit  5,a
        jr   z,cn_envup
        srl  a
        or   $f0                ; downwards, sign extended
        jr   cn_envadd
cn_envup:
        srl  a
        and  $0f
cn_envadd:
        add  a,(ix+c_envsl)
        ld   c,a
        ld   a,(b1)
        bit  5,a
        jr   z,cn_envadd2
        ld   (ix+c_envsl),c     ; and it accumulates
cn_envadd2:
        ld   l,c
        ld   a,c
        rla
        sbc  a,a                ; $00 or $ff, whichever c's sign was
        ld   h,a
        ld   de,(envadd)
        add  hl,de
        ld   (envadd),hl
        jp   cn_mixer

cn_noise:
        ld   a,(b0)
        srl  a
        add  a,(ix+c_noisesl)
        ld   (noiseadd),a
        ld   c,a
        ld   a,(b1)
        bit  5,a
        jp   z,cn_mixer
        ld   (ix+c_noisesl),c

cn_mixer:
        ld   a,(b1)
        srl  a
        and  $48
        ld   hl,mixer
        or   (hl)
        ld   (hl),a

        inc  (ix+c_samppos)     ; on to the next line of each, looping
        ld   a,(ix+c_samppos)
        cp   (ix+c_samplen)
        jr   c,cn_orn
        ld   a,(ix+c_samploop)
        ld   (ix+c_samppos),a
cn_orn:
        inc  (ix+c_ornpos)
        ld   a,(ix+c_ornpos)
        cp   (ix+c_ornlen)
        jp   c,cn_shift
        ld   a,(ix+c_ornloop)
        ld   (ix+c_ornpos),a
        jp   cn_shift

cn_silent:
        ld   (ix+c_amp),0

; The mixer is built a channel at a time and shifted down for the next, so A
; ends up in the low bits and C in the high ones.
cn_shift:
        ld   hl,mixer
        srl  (hl)

        ld   a,(ix+c_onoff)     ; the vibrato's switch
        or   a
        ret  z
        dec  a
        ld   (ix+c_onoff),a
        ret  nz
        ld   a,(ix+c_enabled)
        xor  $01
        ld   (ix+c_enabled),a
        or   a
        jr   z,cn_offon
        ld   a,(ix+c_onoffd)
        ld   (ix+c_onoff),a
        ret
cn_offon:
        ld   a,(ix+c_offond)
        ld   (ix+c_onoff),a
        ret

; --- the chip --------------------------------------------------------------

; The select port is $fffd and the data port $bffd, and a machine with no AY
; decodes neither, which is how this stays one file across every machine.
; Register 13 goes out only on the frames makeframe says it changed.
ayout:  ld   hl,ayregs
        ld   e,0
ay1:    ld   bc,$fffd
        ld   a,e
        out  (c),a
        ld   b,$bf
        ld   a,(hl)
        out  (c),a
        inc  hl
        inc  e
        ld   a,e
        cp   13
        jr   nz,ay1

        ld   a,(envwrite)
        or   a
        ret  z
        xor  a
        ld   (envwrite),a
        ld   bc,$fffd
        ld   a,13
        out  (c),a
        ld   b,$bf
        ld   a,(ayregs + 13)
        out  (c),a
        ret

; Silence, for leaving with.
hush:   ld   hl,ayregs
        ld   bc,14
        xor  a
        call fill
        jp   ayout

; --- state -----------------------------------------------------------------

pt3state:
chan_a:     ds   c_size
chan_b:     ds   c_size
chan_c:     ds   c_size

speed:      db   0
musiclen:   db   0
looppos:    db   0
position:   db   0
line:       db   0
delaycnt:   db   0
tries:      db   0
patternloc: dw   0
poslist:    dw   0

noiseper:   db   0
noiseadd:   db   0
mixer:      db   0
envtype:    db   0
envtypeold: db   0
envper:     dw   0
envadd:     dw   0
envslide:   dw   0
envslideadd: dw  0
envdelay:   db   0
envdelayorig: db 0
envwrite:   db   0

; Scratch, all of it only alive within one call.
b0:         db   0
b1:         db   0
tonetmp:    dw   0
spec:       db   0
prevnote:   db   0
prevslide:  dw   0
pt3end:

; The AY's fourteen registers as they are about to be.
ayregs:     ds   14

        include "pt3tables.inc"

; ---------------------------------------------------------------------------
; The music itself: "Time Up" by shiru8bit, from OpenGameArt, under CC-BY 3.0.
; https://opengameart.org/users/shiru8bit
; ---------------------------------------------------------------------------
module:
        incbin "timeup.pt3"
